const USERNAME = "USERNAME";
const ABOUT_DATA = "ABOUT_DATA";
const OPEN_NAVBAR = "OPEN_NAVBAR";
const CLOSE_NAVBAR = "CLOSE_NAVBAR";
const PRODUCT_DATA = "PRODUCT_DATA";
const CHANGE_INPUT = "CHANGE_INPUT";
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_TECHNOLOGIES = "GET_TECHNOLOGIES";

export {
  USERNAME,
  ABOUT_DATA,
  OPEN_NAVBAR,
  GET_PRODUCTS,
  CLOSE_NAVBAR,
  PRODUCT_DATA,
  CHANGE_INPUT,
  GET_TECHNOLOGIES,
};
